spring.application.name=NutriKids

# Permite que o data.sql seja executado após o Hibernate criar as tabelas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Habilitar console H2 para consulta direta ao banco de dados no navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
